# Generated by Django 3.1.1 on 2020-09-22 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20200922_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicines',
            name='medicine_info',
        ),
        migrations.AddField(
            model_name='medicinesinfo',
            name='medicine',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicines_info', to='App.medicines'),
        ),
    ]
