# Generated by Django 3.1.1 on 2020-09-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_remove_medicines_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicines',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='medicines/'),
        ),
    ]
