# Generated by Django 3.1.1 on 2020-09-21 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20200922_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinesinfo',
            name='medicine',
        ),
        migrations.AddField(
            model_name='medicines',
            name='medicine_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicines_info', to='App.medicinesinfo'),
        ),
    ]
