# Generated by Django 3.1.1 on 2020-09-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20200922_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicines',
            options={'ordering': ['name'], 'verbose_name': 'Medicine', 'verbose_name_plural': 'Medicines'},
        ),
        migrations.AlterModelOptions(
            name='medicinesinfo',
            options={'ordering': ['-price'], 'verbose_name': 'Medicine Information', 'verbose_name_plural': 'Medicines Information'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
